-- CREATE TABLE AND DATABASE
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities(
 id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(256),
FOREIGN KEY(state_id) REFERENCES state(id)
);